### ISSUE TITLE
Any plans for adding more fonts?

### ISSUE THREAD

**Issue by kartiknair** [xz/fonts#2]
Hey there! Love this idea, I was wondering if there are any plans for adding more open-source fonts. Also would you mind PRs that add more open-source fonts to the repo? Sorry if this is off topic.

**Comment by 3x** [comment]
Absolutely! If there are any open-source fonts you would like to have added, please make a PR. I'll add contribution guidelines shortly.

**Comment by 3x** [comment]
Added in https://github.com/xz/fonts/commit/24bf7d0f93c9a24cf5d2264849c16d718ff67955.

**Comment by kartiknair** [comment]
Thank you so much for the quick response! I have a few open source fonts I would love to see in this collection. I'll be creating a PR very soon 😊

**Comment by 3x** [comment]
Thanks for contributing! I'll be re-doing `index.md` and `index.html` today, so if you'd mind leaving those as they are, I'd be more than happy to add your fonts once it's done.
