### ISSUE TITLE
Add my favorite fonts please:)

### ISSUE THREAD

**Issue by shevernitskiy** [xz/fonts#8]
I'm super very love your project. The world deserves open source alternative to goolge fonts!:)
Could you add Lato and Marope fonts please?
Lato on google fonts placed without Cyrillic, but current version supports it.
Lato: http://www.latofonts.com/
Manrope: https://manropefont.com/

**Comment by 3x** [comment]
Thanks for the suggestions! Haven't heard of Manrope before, it's a beautiful font. I'll add these tonight.

**Comment by shevernitskiy** [comment]
Thanks! By the way, manrope is variable font:)

**Comment by 3x** [comment]
https://github.com/xz/fonts/commit/01128150a5a30f1bb37201fe3579662a167556c0 :+1:

**Comment by shevernitskiy** [comment]
🥳
